### ISSUE TITLE
Optimize layout.

### ISSUE THREAD

**Issue by KanzakiKino** [KanzakiKino/w4d#3]
Layout is too slow, because now it calculates all styles if it's not changed.  
So it's necessary just to move widgets using shiftChildren, if parent size is not changed.

And resizing elements is too, add handleResize and handleMove methods to improve.

## ToDo
- [ ] Add handleResize/handleMove to Layoutable interface.
- [ ] Implement handleResize/handleMove methods to Widget.
- [x] Change Layout to just moving, if parent size isn't changed.

**Comment by KanzakiKino** [comment]
handleResize/handleMove methods made layout slow. So it has better resize elements everytime after finished each layout.

**Comment by KanzakiKino** [comment]
And checking if the owner is dirty can be optimized more efficiency.
